label scene_2:
    "A large door stands in front of us."
    "No matter how much strength I put to open the door, it won't budge."
    a1 "This door seems stuck."
    a1 "Raymon, do you have something that can open this door?"
    a1 "Like a key or something?"
    m2 "No, but I do have some oil to reduce the friction."
    "Raymon whips out a bottle container labeled \"Motor Oil\"."
    "He then applies the oil to the hinges of the door."
    i "Why do you have a specific oil for this specific moment?"
    m2 "I knew situations like these would happen."
    m2 "Knowing old doors would rust overtime and therefore hard to open..."
    m2 "I brought it just in case."
    m2 "And look at that, we're already eliminating our first obstacle."
    lucy "He is correct."
    lucy "As much as I question myself bringing all of you here to danger, I suppose you three can handle yourselves."
    "The door finally open with ease, and it was time for us to venture through the asylum."
    lucy "Watch your steps. You might stumble upon some debris on your way."
    #TODO: play sound big door open
    scene bg asylum with wipeleft_scene
    "As I entered the asylum, I saw the remnants of its dark history."
    "There were old medical equipment, broken beds, and strange markings on the walls."
    "This place screams prison."
    "Despite the grim atmosphere, I carefully look at my surroundings to see if I can find something that can help Lucy on her mission."
    #TODO: play sound camera
    "{bt=2}*click*{/bt}"
    m2 "This place looks straight out from a movie."
    m2 "Oh, and there're some rooms over there."
    "I opened my flashlight and pointed out to the rooms."
    "No matter how bright my flashlight is, the room I'm pointing at is still pitch black."
    a1 "Ugh... This place reeks."
    "I don't blame Alonso. I can't even focus if I can't even breathe."
    m2 "Hey Lucy, what's the goal of the mission anyway?"
    "..."
    "Lucy pauses for a moment."
    lucy "I am looking for an artifact."
    lucy "I was informed that it was priceless, and tasked to retrieved it."
    lucy "However, I am quite suspicious that an artifact of \'theirs\' would end up here."
    a1 "If it's an artifact we're after..."
    a1 "Let's split up."
    "What kind of suggestion is that?"
    m2 "Uh, no thank you."
    m2 "You're asking for death."
    i "Likewise."
    lucy "I appreciate the concern that you want to make my mission go a lot smoother..."
    lucy "But I cannot overlook such a lousy decision for my convenience."
    a1 "Alright, fine."
    a1 "We'll go together."
    a1 "[Main], do you have a preference?"
    i "Well, if it'll get this job done sooner, then I don't see a problem."
    #TODO: screen map